apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qoves-app
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
images:
  - name: qoves-api
    newName: registry:5000/qoves-api
    digest: sha256:8c400508200f3014869e309eaa9524b68fabce3bb7a91b3f9f8389fe95ac0243
