apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: qoves-db
  namespace: qoves-app
spec:
  instances: 2
  imageName: registry:5000/postgresql:18.4@sha256:cad808790906aa770e1cd27100f1165703b91d5c1fb198ef1a94d719f5ceb942
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: qoves
      owner: qoves
      secret:
        name: db-app-auth
  storage:
    size: 1Gi
    storageClass: csi-hostpath-sc
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  backup:
    barmanObjectStore:
      destinationPath: s3://qoves-backups/qoves-db
      endpointURL: http://minio.qoves-minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: db-backup-s3
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
    retentionPolicy: 7d
