apiVersion: v1
kind: ResourceQuota
metadata:
  name: qoves-app
  namespace: qoves-app
spec:
  hard:
    requests.cpu: 1500m
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "15"
