apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: qoves-minio
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
