---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-database-url
  namespace: qoves-app
spec:
  encryptedData:
    DATABASE_URL: AgCkn+eoHLmfIt7kaU2Nt8of75sRBx8X9AbMe+2Qn7+KQ5qdnxCzvyX4CK+dpmy1sroIUKWkGNFWDirchgQIlGozSjfXlP3+JzdvEeVAvzrqVDMK7cDAAjIQPgJ7owS06ko9/YmfqNLEZuOeQL/1dfJzVVOUaXkhqokjMh9FviTjnUo9IKhzJnxNfoMUOlZDRCVkzkFui/Q19fvc3WjIfUN/Fnm0N0AQZXEpseUIWazffeWaJv8z5nei1yVFAxFjnM5iJnHoXRmEpVgiZBW0x19RAU1YgPf+Umd4GDxTBuzBCP31uSGuWSx4lMxajBM6RqdZNKasKgg6qPU663LduNmEzL2EW05v6ZUH4IrCMzWboHJjlukhT8+68Krqy1w334ScGJO3dj781tOtJJGr4gn74jMqpBXJof5bWOrtxlk1I+iiTQF1Gx57BdYTOI8nr6hLmiWcvm12HMRakfka0bQ1DivB8GYDRufI8xbOPWQuve8ANFtgMDbtkwS42BW2p+Qp6wixSAj6I3bRQXQWE4/w8DsEndx0uiulib1HAW6ch/U/EhlrfIaXnT9ar+eHCMtJQfypf6qdOIIgV/jkZjklEO3qd9EXdRPgbILUu+T0AgMyo9JJB0f6IfQGOlFShkZqmfhtGqvvFiLSXowQE4q8JzWoC5FswjRhHz4JDTVP/GblldNfJ30MAKNNZOop2zCl0EzeeLlhOBaLtlYYHQzrZ4M3ISCRZZwJ7PTN57c/fbH5kKEwczVRtT2fkZFhHxljLzvUgEve3RA8UONdjJdRJXfFKmZyXehHlAQgioRF/BxWlkRK3Sg6+FAvpQ00KNLLO2kfyEVjElfkJchbKw==
  template:
    metadata:
      name: api-database-url
      namespace: qoves-app
