---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-database-url
  namespace: qoves-app
spec:
  encryptedData:
    DATABASE_URL: AgB7Vw/98ndiHWaMB/SZefaQBPLmwPj6hp0fOeLwpM35g9Vt+Sw0tqKp2Ld+wDabJcVvVtCXSN9b3jMsQVT0D8tqJ4zUz02PBc1XP6wKYUotd/Rx0uhE/OK90Y/g+YU1AcOYAEeSUz8bYY4Jef/REHzrSJnmJrbcenSkR9yeKy1/Qv270Bhk5hoQg7FyhjEtRI2tgJyzciFaF4VyfDKEWAXp7Dccn5Abt5jFXPFFgL/cmBSmMYcM6HNIS2iiJH2wUGVP++CiBVSlBDJ5ABWWSg8sUJwntcGNTvmSIAnSG6yefoQ7tHHuqpea7TmwMqri0NNY1/x1tdGOuXxJ708e7SCWd5dAj0btDXP2EWjdue2JUKm0/PGlGRCZG/+cSghFTYI4FhEwvTXYAVmLOsr5oSRsnLGlOvlzvsSKZfoDeHQyZaSbXxY5Kje9/vfns3IUJpB1UXUEDV3b0tzjpEt4rKBTK61vS9AANpseK0OpZ5eTjaWVwnfzOD/oKXStPo7G+K1lPYi/VFFMtApxzKtmYx9hPWnD4kXrEnhnSTR2kcNoe8fasqTJ3+VP7Lg21ocfmuC+jBYFa01coco7k75BmhHtbx1yDzrGYJjVafegIgVJG3FlYU60XC1t0zH/MdQAtKeye8IX6VbsKUiYRPNu++F34NnyOtw4pElGXrjYqAzdryHfU+PT0+1K3nOCWr3PErDq4xrYGCM1g/WSw0ces3C7g45kP113Hmemd3I8qoC+eGhodF7WEglUGizsnuXaRlM3sKpCceUleHcFQLGJb2uzMhmSUaneG2gihIahZTvj5Hu/1nKbakFbBQdLPrmykhMCibafX4wBzt8HXs/Smg==
  template:
    metadata:
      name: api-database-url
      namespace: qoves-app
