---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-app-auth
  namespace: qoves-app
spec:
  encryptedData:
    password: AgA998X5meH3Qmk+6w2fzVDM9jBwEm8KQ+uzXFLAD3zJBWD2YUCagf0GUCOIR6+QC2vFlm7CMZvW+5dPzgHhCMjJEaYetznEEQd0HZClBoTCzYBK0xQONe+wph7UFYp0z9UHlfPMMaq8VMhH00+xlZA6nyeXQ2fx+i4hnBGoJYipsx/wfbiOiqV1nmOR4RMmmpYsxQjv/lasugY1o3E1lDiCX+dr1sqVXwQFUjASTkrd1ZKni1LXDnUXp8J1HjNEBVqyHagyG7DOaIVTRA+9PQeyLtIIBbddL/oSAiTaXd+onv4orIJcape3C3uGDiWK5v2fgE6rzxVoeDqyu6T8Ait1pxOsF4JxcFNtwubd/OaEcAF7xG5qMXNjrODoDndcwpg/ldYPiXeJFUXWisVLzZxVbpxs59vCwtQHb60Z4NEPQBUOaQGwVWYbD8A3ST0yhfLMjnlLkjRdh8VzeW1XstEWzHJaYePUFmAoVtsSYpyzTCBnUQqnMxxU5N6beBhngoD92ytarQKWlyCMAFryw8JC3QQYtqZIg+hFLEJOxHFyLmwcTysEFdNN+jYR4P6u0YnYbfwJdkN7CGmkP55BCDip7rwGc2nukon/p1BDNyYLzK84AQ8ksk4x9Eph5J9RCr1W51Mp3VGQHGHl87qSbKfeN85S018AE0ol6x4lwdMdic1wd5uNRA8iYdk/ZUVn7QyuFB5/eppEzdz85Gpl/Za7Ffkz4U4YrzNnsyBJ1k8OSxa8LqP6Jwad
    username: AgAjngdaMUirsvFppKb+uflPtChm0sb+w3WFYT+OCHqqgLy2MSJ6scTYpawYlGifSF+VGizM7umOZ1HUR89QYcfBEN/vlZDK+zlHk5kKeJNFdT6a56b7hxyaLo0XNo9EEgmVo60Mw19Q/ylEjK5VWrsGJcOQQc2C4ql2sis4V+ZcoCRBO9CfRHvFD+lAj5c7Dud9rTlLoBOdh0K4tEqiZpEvNfsMr+1SVtZc6QVlQhmmt4oG8W947CA1LfcdQam1QjI3c2u4vhvVVrr8xhsaMXnnzm/8mIt4539y3mshB+qtKF9tGoib9KvapTHV2797eLwLaF9mFdJXype2rFAMlSvwP6vtCAwp1iGa0opZ8SkqGVf/tRyHTKEgpyRlWdEw9M9XSSQV7CiCCt3jmp5Ujt2RY3pLaXSewER/ylp3sfCum77kE/t/Cp9k17E1etnLUNIc92mCMNksF3hburkZhqQUSUF2/Jc5lh3okJKw4hzWaV66zgLooCuDkUO3hLsg8WjoPldiwy/BirMaCTY2cukTSiRsiMk75ddD6fNrzmI3owUUL7pM0oayjk3s49MuXeWfefJmeEarf5AXXgj9QsWmk0FXd9J7KCmA7x8dEJfJ/w1atG8icP3oeNnfw7H1BFrQ+FVdDD70jGvJnWF6A8Lg+EdDCSAWa1DNllvhWHcg7Wok/wC8uGG1dgR8Wd+2xIdtrIf2Rg==
  template:
    metadata:
      name: db-app-auth
      namespace: qoves-app
    type: kubernetes.io/basic-auth
