---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-app-auth
  namespace: qoves-app
spec:
  encryptedData:
    password: AgC5uQhjrLrYt2544yfqyePoS6uQbzm8fFUZT1C/agk6tWANFT8sCeHb820wTkEpLaus7boddBSuvrkSfRkhkFduO28Hb+8ihA4yA9Ou8wTMf0UtzkiGFKoGUOh7jOpsqESZ3bL48J+VQSsM6fsqz1nYOqpKoAHGay6a9O+M7M4LpQNcB92CIo5MtTieWivl/3P5wRozGyZwit7DAMhBkeEYK/QOp979o4M/M2UBbAAv2D0hb+VjO89oSI4ZhSnDW1hG1mmKBWRlTZTL4bF+iFA/VHb7w7wrH5fPBHVRw/fx6UPxu4OoMrP2unLO7AuuXb24YQlrm7c1hzDf3b4OiYiYjGtVJCcfSo9L4VBtTr4efdj8CEG9OFDQa6fIR3QxqqQ/297UlQbxmhqaJ5DDpKxAKg8qypHJ4Z9RCtxKLSkMJT00H9NfJMxkDdImHnd8+5blBUYVrJ10tiUVaY0PrgDNNcifaiisB6xNNsGkoGVT6Rl62G17GhtMm6TmvP5iFjpXiLoqVUHE6h9FuEX6+cH6gzF8/3GD2ueRCrgEgQkDneiH+KtIl7WZMILbW/EAaugefX4u1nKr9eeti5ZuiO/tcDMG07wB5JZHV56KVXCcODSkExwwNLqoLguGPCj4PpLsV3ZAlxIlZ8r61/dMb/dnkCetjhT/IEMYSP0IGd26AlynQ1ZJIPBvbY1QPPfFVO67RDDqNBiMYzkQ+6kHEk4hcxqEBrIRV07M5Co1FaBPAk4CLujy4SNI
    username: AgDPqd7ADksq8Fe4RFD3f5UmI0XbponxWbdJD223eUFIoKUU2WVTTaIBoMtlNuuZP0s9KQD7A/vYUu1rc3M9omK9smyNc5qQIq7QkZz7DlPavKPbKKLx3NMzACsz3tLMZuZNjD0PhqHMyz2Dc5rAxSJbmBuo5s3B0UhTs6c3obN37GGYlPz7tJ1r02ES+bhqM6WUvQoBATQSjSnCSGyY9Jh7XaJ7Er1jNI8XqFpbtX+HOozsmMAvUbrdF1YkiQ95RkfwsTKWiuXIwYShEMOldmb/L961Z1FLN/axul6TccAvuRLt7NqA0ldmoJCf5xejRrqbujfrUj9cXktQIzTiBsVmU+f5Y4ymSOk65Mt6jFR+ktb4VmhFGF4WRFqkhC2gH7uxwkUT6U2DIHfwjmDkfgMewyhkfva7beaZDohvFnfOdhtJyMyvu50be5NUw+SzRmKj5shADsiKU5EkrrNHHmSnj/t86NHBKMkGWXCymW/PZPVL3TxoHkDkAv9tjPz98JVV6ZSQ5RcwWDLyyVxQDWsTh3rH9u2LXUK/iIiTieMaPN6TPd48F1UHvPMmXfQ2Z2YCy8WmjT14xgcpiqv7UEengkCnl/ErwwoOpaxd9VTWlHHgIwQLx4UDZEPQp+bqzVWeLJ6l20CP2MwxSAeeuQzE0iH3w13urzoOItiTYb8kxlJgimGu2Ql6ZFWjZHTvK5JNU0QTlw==
  template:
    metadata:
      name: db-app-auth
      namespace: qoves-app
    type: kubernetes.io/basic-auth
