---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-backup-s3
  namespace: qoves-app
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAyqdRpmzmlJbJLKuyBty5AQYu+m4nwY2pVk56sZnSmIEg7dmKJcQu25FRogMqrGXLBGSSe07ze9vB43RZOO2zY9D8j3u3OaeHmY+RXcXFuo/zRLYeLx2BRIyIIjBaVa7mIAYj2iGVjF0JTc83VV5uecQiW616NxVYQVom6L1+GkeIgfuAyJzbrtbIEaaJQve3kqnLKX84eGQwMf2xBhUxI7mXlmJsi/nY1jhOGNKJXx2HHJ9ogMX9R506IFIhlOVuy5Mmm6oC74uXyqPbKEUHEoDQ3+2me09+22stz1k9sHwOnKwXCVAbWqmjLoyY4bg6VDbPC4uTzwJ1/bD/3sGEQZHRfYn/pY76WYcx3h1YrC067AEZEStgi29DgxddK6+4f/5NrSpqW+gg3TAdZx5px/Rwc8l5IvWrpF9pGdKGEqV1wKPQZ0KHYJ5GXcOLdRjIGFmea8dPr/TOqEXjxomUG1AO8K+RhrakfgG3W+Q5wAzGM8YJ+3azoSoHTmociKg3KRHhSmitj01DGRE7sZgbuzZpodGGusEVu0r6JFdlISaWIRnLdRmV6jOneO+RxW+/7/kXeDJ1epnNyy2UQaE2hb1wmy8yFzeJM0Ri5+bMoCchfWruyxSUIdjLu3t/2JmK9GaO2qWt9Iw+B6zAgdRSeK50I9TekTL3fFr5IlRUJHR93v+xym7msbewb8dCJ59OyRumuI61E37f6ycw=
    SECRET_ACCESS_KEY: AgCUt2DEXjPEUM4tiKk91Tv19Qu7/p3vVUOWGFFsxjrHMRozB6R9ugc5jmamNqR8jrfaPIkFHycC4ly/kOrZMGom2BthMFzS/l8YXW57QXc6ImQiS3iKWo3Fs3vBxUO+9r14D5/Agev+p1U75tZkiVCbExwoeJEkgwgPcvtWuyXNFWSxGmGesVHaa7iFdENwY4yVl1tO0Dn8Q3pXTEUulzt6gIbpaD9DgjcNQtDabux9Zo3z8Dr/uYK38ylRZz/IhO/eLZDVPPo2xwVv5cwM9cFp5D73w3CjEQ/V4NE/Tjv5vUb48OgoBiQjc/2DYsvsvUIJFfSl6zgsFdBBMB82layW4x1IJCM1DNUSnxJ1uuBL//e2vDY5+83DyHbVsN92xbTUaj8Gg/ajHnSlJ8Qo55Q9aZWUMof99D1JBVAVZEe7KATcQdUw/SW925IdmFJV0MKzjcqW295ofN17ig5PMCbG1zjPKltoELbwQttKG9VbcIPgikI46q+murPdrNCe3l3C9eRuMzV/pbNbl2d9ofLrzVTxYwHOZ6sPbV+biFRKKyfyB8qA9ImA4l6anF/d3Ld+f/GhicfKHSA6yDdOQPn25pxH/hk9Nzrbp+1APvjWUjAHgM5aOg2Pe2Y70IZMVUjG3Wv2t4y4DPDZGKCvEcYI7YGpOnqoVfEtlNbPPbTGy31NtL60II7cNEqOmehL49AZWhIlOr/4AIsr2GJCmxqncm+ge9AynaSTtvCR08qsBx0n+fxioGXQ
  template:
    metadata:
      name: db-backup-s3
      namespace: qoves-app
