---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-backup-s3
  namespace: qoves-app
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB+XIiOKvwZrWIHKYyKY30NFV7eh5JJUtI56i0xRHjA5feZ3muIjFLa6q8rvZAdnGD0KKFYStDVrcEaGgCtSc8oUbsKQB9FFkXni/VzeuKbwUsmfYNoPVknAgrVVW6yrlwGVCWMt4v5H4YyL9y1ho4KEgXkePpwELIVIeLgbOQRqxC/2HtlrLHOMjS0iiOYu3MHNxXhgNYQ6iWoVg8hzu0IDaTB/NJjTVRkDcwzzCRPax8Xmw5IzPey94gCpyazs9c3PSBTmZJl3YpiTJCXa86Uq6FuKc4IGQIXYXjyAigdu2/gq1mBT5dcpjwO4h4fdOfhPK8svtSkahi89aeJXzndD8MhSl0oqhmeHV/PsqEzfmWbcYZr90M27g7tiLLIVhGS4EQa+VFmXLgcHA0J3/Q0dGGKdAIpr1nof3oup2j9Z97e8kla4OUBPa3fAH58zoGHm5dEl7qdEyff491p+saN9uxO5olq3t1EZBB/9/ppb+b8/vBknBeBhLwWySf923CUeCQONpfwEUF2U/MvRshftML3ucJiZTQjbfQ3O4NrwJUYVcXvBGyZ71fJp5cFqt4dlJhFCRRgy+ptgfyXPizbr23W+wU/f+WyKxXZWQyMrwPSTTkp7VSARnkqSsaRK2Uep79SjXjoUexP020nrYZBMhO/Z6jbhBvcYih+XLPDEHCo8E3ac1CcV/Dlo2hf6aouSFnx1Zd1wD4jTZo=
    SECRET_ACCESS_KEY: AgCvJLk87byrFFHM0hORasPnsX8HO9jRdPgMIZFEdsA6+OpVplu6tuKIvpPA5lOJpRr8FuIo9MfqARnISGsAnB6loxcsdp0g/U1xNIi2nJH8OLzHGcLH8f4Qdne85eJ/yHjdzl+Wumjepu4Eoqc6zR1zVOVN8FI6TF6T9xASPcE+BpXYJzDzpX1O7/1Zu57bJDwlf89uRMQ398OrlRvAbAH6gzCtkeehbq2jJZ9I5nSFUXJqHphymBuWyInS2H5GArsZS4vBN1SS+8LrqjUkf5NtX7EY8vipYEgB2ssbBYNlvB7QBPDhnJzyLBVJiaQOcPVgzAR1yL49v+IPKyzROWVNghDQQ3P20GsjLQfTehO24RqBOGGpRFX/dAdpBnbpNZZJSOt8o90MKhSwSBuJ+OXNPfo2UQqpce8Dtfb653GsdCPtNDzPBmF+odzbb9YPGi92aRu/bWhGcq2ppRAxgMFWxzSevlraFXYJ29Sy3YeKWJMBe6wIqo8qITF1W1ylifd1PAu+JTnRwdoOTJigs62KMpWnuu4qUeZfBU+5dMO5fChbZ+Qr6jBPh1ZKAHIM/pg0F6YX1jRbhYUqVJcNhDbN3u4eGqo3BIW812t9rovr9rZhcxrEDYlUoFuUj7uaJt08eJHU7sM0LtMuq9XWlejhs2bp08zPytoI4++DuYSAsV3tJ5vXLIP7s0LktOwwASHxCSj9BfmXbQ8eBM1odg8pjgQkYo8MM/jkP5YAtpmv3CeR3YElJLoV
  template:
    metadata:
      name: db-backup-s3
      namespace: qoves-app
