---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: qoves-minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgALIAy/7/EGDXyznQ6n07qq6TMxOqu6Qg9q8wMLM9ke/9lvKPb2jHD2sQKWTvu0Hor+a0vo6qBbpk8AO4oJHdo+bUKAhoxa8v07LS7Rx9AtV4Ou6XU6qBSoaiDj7izXXewr3gLJUxNnZvMY4/PJCmK+Ne/253Npf26zOaptxr4RlWWRGX8XTcbAvkD9YHjH9nt+ds/b8u4ORNONxgQLcH5Pz5MBDDx8l4hr3w4k+UYcwHGqnd9C9foEJ88LzJdCR1Mb/1yUtyA/eZd6cjZH0OZ2duoGiIJ66kp0WmMWFikS9CZ12/P14mMXsMSxSqUcpl+8VoiqGt8qxon4QB0KXhaKj41LiBproNE8DSoa2AyoGMip+ka/40lOsegzUyS4nhTu08mr277hO3JqmxjDzd+B7Dp7EmEWis5b81pp0VsE2pZ+drpGRrOv10/3kBI3UOZf0f5QKK1DAdeX6pwXGgxZfjzoaCqS9cTTjyLTfAo9STwZ1GUIT64w7s1FxkfNN/RBlkU5tUcKCoMPTPxGNWaL4tCLY5Qp1ByEhP6zwT9ImsXPO2QQVyaSJtXCdxKtgmxJb82CmpCsAO/l1iH7lcFWBk3FzwMeS9c4IZVYiEI4gv5edrO9vEHCGNuzczlnzWdBpnhXXVnugM+UHo+QrGJmpC7gy5DzlQa2w55EvWoYFwxharx1kxPDIuYQgezKwf5/INWChRCiS+IzmLa4dRMseNJP0BTyUHCvA8OAiSrOLb7wNOG9jHwd
    MINIO_ROOT_USER: AgARynd5e0JhprnseHWO3X/LBMDUuR00cd1xFXt9t6I+d7uadN1o9JdYsShbR16ATbmgcpci07gcGox0LDXVrbGmilH8YLWd834EmjHDLuOXVvjYclJKz10mHeT1tY/wu/MiiiSWijoIEDwVHBq3bSmIWkG6XjPb3Jt5X6txufTkKUosI/Vavboi2ZnozRAoymODuaExutnP7NL6JcwTApOe5U8Zbf+diHzx/a926YXBZ/tQh9nXLb7PJ+ScpeHRWN5jZBsEtUbpP8qf9K5Ky41yAU+H349+3AvySJEXrxGt1cThNci+VWkcIo0b1ukrDi1yoUqSc63hFTLRKgHoSlcEOC7hxB3vBP+8BeWP7g2ummZNJOoReM8+t321J1BWkfSGVh4oU2dMSXm0xUQN8uUvDUmT5n+IgkBiymYXHkig2QKePE3mctlvWetOD2346PnRRHXvkASPahcXcblB8A/x8bsbQolZsS0+XoLwBIv05sqj7Wcgn+sm5qyPvWQ5ybu6t5G7K9o+OOe2Xls6ZNgiKuwhTp2rwEkC1m5i47HKHCiK7zQ5u6Mwv3g0yY+yMvH+Qh/O80/tBLAE8HK5plUY1Yiq2zaJNAifFt0rZoU2yn2REA2BDjBbUnd792FMhqcx3xpR8MuDK71CrJtEeEbQxyN3qh+Gvp5VZlToHQNv5Th4N0iA76vq3kSjjIZ+Rua/lW6DXHNm0c3CuOg=
  template:
    metadata:
      name: minio-root
      namespace: qoves-minio
