---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: qoves-minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCGd4skCJF0QLDGAsY/jkCWndZArt+O6SldsUDnPi2y84XhV+0URclFleQ4HsI5wL+ePWGsKtHbOiLLdFhtK6OmJKhBrGCMAgxBPZ0a82i1Nay2/AkNTudTocnZKruhHXPuAr0C9hIGSS0yTVYHQUcrUBi67PTwUcxrd5gMVS8SRerqgHpDz89s4VGuwVW+HEID8Ev/pwnwOrB6DvXNxkb4cU0rmeOoptt+4WwuQoP8V8Hy1MulSRkHhzINPkFJRbkKsScVnPCTkXAMO4Potj3UZpyaKpkGF+OUpSCw/dlB6wrqlwUtnouKT5xE9RplXDOh7t8hwte3cyaWXysDJRWTjrVBGEKWVYGrEsEf/x2pxih0fOAPEBqny66hDd2NIngsJbOu57lni1S6wfboFwYwRPKop7tk1A1ocqwDcZ1Qle78KEf+KhiNmxfCzFiSm8grdObfmk46qo1bedDoD6AzYAlMD3X4P2E9pWdCh34PcGgGqodqyz6ngeb/MzJQtaBeqDQkXPCYrHo9LPfBn5uoOUEuE67HLh6+IavMPOtSMC1BT4LKKnMu8yFwldHsea45uwqH7QPpvgbFrCuK3fE4FBJYQxizgY7z2w/WVlIvCkPcXx3d7iosLLqO62YqK7QmTowt9aI4sUK94r7pWn1siLKAFWyzmAuQ8TrYHAU5KqJt3Om75UmfH2CMp34ByFw/tuFI771oiQgej9bULjaynJig/07GhibxJRUhPAgDmfQgE7GnYwq5
    MINIO_ROOT_USER: AgCiNX0zr70Mh6r6XACnRDb5neCAUhBwOIX+J+DbSdRm6E/T3YnVOnPnkq+6SsaJX5XbhUzOP5RP2+9kuOUfxRsUW8t5Dm/HCYFb+xg5Xlxx1YcmZfZ5I7v6HBT33dWy/3MOgHWfTIas6lDEfy9IGgnQ3r88q3NG5l46/kgXaZHiVYxD9nmtlUNheZJrUgrGTc+SiGrUCph9nqc/m8Gb/In4dIFsCQS/pgGpJKMWIRtnh1JiYKnNoHFp3YWoZHADT0haBhWfLO/wmSEnsPRm/F7ynDNKvN6QVR/YlhNTAlyhEQgVw3uMNbrNopENA+J7wRWzyGrwshjju0K3zzAvVA3JLBP154eCA4jefqDDUSiVB+OPipjiBs4lms3ZzSptqTlZwYxk7XOjRFvsKTXzh2UMuuuanpr3eLZMh9c3SPPVv6FBECUFAPKXI8vNebxsBEDl/qmH7eYhKjymwBJYxnn6G+46wa4s4hiODu6mVe8WMTkwvN11GjNmEZdHlmxCkhW8VdKagt6Y5RHoloEzbA1v7dcECx/6orgBoHfW1mH3eA74wNkVi0pWPb/wz7LHNDKPMwgFiyz3vq9Kd8JjYustuKyFkKOMZVCCu/nWHbbsd6P4gYjTjNhqZzDJx+iBn4PRis2ATuVPahd6Gwii2QSMbDUA6d8PgrH/RZZx6tWvtLPEmqThMPBA5wPKPSwgpNMScsbv6XAFm/Qgqfg=
  template:
    metadata:
      name: minio-root
      namespace: qoves-minio
