apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-signed-images
spec:
  background: false
  webhookConfiguration:
    failurePolicy: Fail
  rules:
    - name: qoves-api-signed
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["qoves-app"]
      verifyImages:
        - imageReferences:
            - "registry:5000/qoves-api*"
            - "ghcr.io/*/qoves-api*"
          failureAction: Enforce
          mutateDigest: true
          verifyDigest: false
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1WO4ESjCf2UpQavZWNW2FNrYqAyH
                      f1PJpIqkc5PLvfKuMlA79F7hTkLgiol6H1CuJewIL+LKGknUu/i6daO5Lw==
                      -----END PUBLIC KEY-----
                    rekor:
                      ignoreTlog: true
                    ctlog:
                      ignoreSCT: true
    - name: cnpg-postgres-signed
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["qoves-app"]
      verifyImages:
        - imageReferences:
            - "registry:5000/postgresql*"
          failureAction: Enforce
          mutateDigest: false
          verifyDigest: false
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1WO4ESjCf2UpQavZWNW2FNrYqAyH
                      f1PJpIqkc5PLvfKuMlA79F7hTkLgiol6H1CuJewIL+LKGknUu/i6daO5Lw==
                      -----END PUBLIC KEY-----
                    rekor:
                      ignoreTlog: true
                    ctlog:
                      ignoreSCT: true
