apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-egress-db
  namespace: qoves-app
spec:
  podSelector:
    matchLabels:
      app: qoves-api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: qoves-db
      ports:
        - port: 5432
          protocol: TCP
