apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: db-egress-apiserver
  namespace: qoves-app
spec:
  endpointSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  egress:
    - toEntities:
        - kube-apiserver
